// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'header': string;
  'topBar': string;
}
export const cssExports: CssExports;
export default cssExports;
